version: "3.3"

# backend services
services:
    
    twt:
        image: abhi170599/tweet_api:first
        networks: 
            - spectrum_backend
    
    tfs:
        image: abhi170599/fn_model_serving:first
        networks: 
            - spectrum_backend        


    analysis:
        image: abhi170599/tweet_analysis:first
        ports: 
            - "5001:5001"
        networks: 
            - spectrum_backend    


networks: 
    spectrum_backend:        